version: "3.7"
services:
  postgres:
    image: postgres:13
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/postgresql.conf"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresql.conf:/var/lib/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    # restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  debezium:
    image: debezium/connect
    ports:
      - "8083:8083"
    links:
      - zookeeper
      - kafka
      - postgres
    depends_on:
      - kafka
      - postgres
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my-connect-configs
      OFFSET_STORAGE_TOPIC: my-connect-offsets
      BOOTSTRAP_SERVERS: "kafka:9092"
      ADVERTISED_HOST_NAME: $$(echo $DOCKER_HOST | cut -f3  -d'/' | cut -f1 -d':')

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  postgres_data:
  pgadmin-data:
