version: "3.7"
services:
  frontend:
    build: frontend
    environment:
      - PORT=4200
    ports:
      - 4200:4200
    volumes:
      - ./frontend/public:/public
    depends_on:
      - backend
  backend:
    build: backend
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - kafka
  reporting:
    build: reporting
    depends_on:
      - kafka

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
